Feature/image converter
jpsandovaln/AT2024Progra2ConverterService pull request #7
Opened 2024-10-31 20:54 UTC by Joselian2204

2024-10-31 23:07 UTC, jessicaori approved these changes

2024-10-31 23:18 UTC, Artmo10 approved these changes

2024-10-31 23:54 UTC, yujrajo approved these changes

2024-11-01 01:01 UTC, jessicaori requested changes
Colocar **'image_to_image'** folder en folder **converters** (es decir, que el **converters/image_to_image** se encuentre al mismo nivel que el folder 'api')

2024-11-01 01:39 UTC, jessicaori approved these changes

2024-11-01 02:10 UTC, michelle-gh approved these changes

2024-11-01 02:46 UTC, merged