Change of output directory
jpsandovaln/AT2024Progra2ConverterService pull request #8
Opened 2024-10-31 23:17 UTC by Artmo10

2024-10-31 23:26 UTC, jessicaori approved these changes

2024-11-01 00:00 UTC, yujrajo approved these changes

2024-11-01 01:33 UTC, Joselian2204 approved these changes

2024-11-01 02:11 UTC, jessicaori requested changes
Para poder descargar los frames según por filename a través del endpoint '/download-frames/<filename>', guardar los frames en una carpeta que tenga de nombre *filename*, dentro de la carpeta 'video_to_frames_output'

2024-11-01 02:25 UTC, Artmo10 reviewed
Cambios realizados

2024-11-01 02:30 UTC, jessicaori approved these changes
🌟

2024-11-01 02:42 UTC, michelle-gh approved these changes

2024-11-01 02:47 UTC, merged